//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrefabDocumenter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrefabDocumenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Create database に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateDataBaseButtonLabel {
            get {
                return ResourceManager.GetString("CreateDataBaseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create draft document に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateDraftDocumentButtonLabel {
            get {
                return ResourceManager.GetString("CreateDraftDocumentButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create file tree XML に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateFileTreeXmlButtonLabel {
            get {
                return ResourceManager.GetString("CreateFileTreeXmlButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draft document tree view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DraftDocumentTreeViewLabel {
            get {
                return ResourceManager.GetString("DraftDocumentTreeViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filename filter regex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNameFilterRegexLabel {
            get {
                return ResourceManager.GetString("FileNameFilterRegexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File tree xmlとDraft documentを読み込んでください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileTreeAndDraftNotLoaded {
            get {
                return ResourceManager.GetString("FileTreeAndDraftNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File tree xmlを読み込んでください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileTreeXMLNotLoaded {
            get {
                return ResourceManager.GetString("FileTreeXMLNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HorizontalEllipsis {
            get {
                return ResourceManager.GetString("HorizontalEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しいファイルを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncorrectFile {
            get {
                return ResourceManager.GetString("IncorrectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正しいパスを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncorrectPath {
            get {
                return ResourceManager.GetString("IncorrectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target folder pathに正しいディレクトリを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IncorrectTargetFolderPath {
            get {
                return ResourceManager.GetString("IncorrectTargetFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load draft document に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadDraftDocumentButtonLabel {
            get {
                return ResourceManager.GetString("LoadDraftDocumentButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load file tree XML に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadXmlFileButtonLabel {
            get {
                return ResourceManager.GetString("LoadXmlFileButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meta file tree view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetaFileTreeViewLabel {
            get {
                return ResourceManager.GetString("MetaFileTreeViewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存フォルダ選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFolderSelectDialogTitle {
            get {
                return ResourceManager.GetString("SaveFolderSelectDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target folder path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetFolderPathLabel {
            get {
                return ResourceManager.GetString("TargetFolderPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update draft document に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateDraftDocumentButtonLabel {
            get {
                return ResourceManager.GetString("UpdateDraftDocumentButtonLabel", resourceCulture);
            }
        }
    }
}
